### ISSUE TITLE
Error in Ubuntu 15.10

### ISSUE THREAD

**Issue by ternaus** [Far0n/xgbfi#3]
`
Missing method .ctor in assembly /media/vladimir/1ab2d5e6-a134-47e7-ba27-b2d70ac5ffc5/workspace/xgbfi/bin/lib/EPPlus.dll, type System.IO.FileFormatException
ERROR: Could not load file or assembly 'WindowsBase, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.

`

`
 uname --all

Linux t430 4.2.0-35-generic #40-Ubuntu SMP Tue Mar 15 22:15:45 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`

`
mono --version                                

Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           __thread
    SIGSEGV:       altstack
    Notifications: epoll
    Architecture:  amd64
    Disabled:      none
    Misc:          softdebug 
    LLVM:          supported, not enabled.
    GC:            sgen`

**Comment by Far0n** [comment]
unfortunately, I can't reproduce this problem. I normally see _System.IO.FileFormatException_ if there is a 32Bit vs 64Bit mismatch, but it looks like you run on 64Bit. So that should be fine. So something is wrong with your mono setup.

The best I could find is this: [C# driver mono compatibility issue](https://groups.google.com/forum/#!topic/mongodb-user/dtDH_t16_gs)
